<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Respawn" Version="7.0.0" />
    <PackageReference Include="TUnit" Version="1.66.8" />
    <PackageReference Include="TUnit.Aspire" Version="1.66.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HallRentingService.AppHost\HallRentingService.AppHost.csproj" />
    <ProjectReference Include="..\HallRentingService.WebAPI\HallRentingService.WebAPI.csproj" />
  </ItemGroup>

</Project>
