<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>d2523a83-d213-4d51-8ba6-df2be4375c64</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arshid.Aspire.ApiDocs.Extensions" Version="13.4.6.1" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HallRentingService.WebAPI\HallRentingService.WebAPI.csproj" />
  </ItemGroup>

</Project>
